# permissions for end users to edit wasps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: wasp-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: wasp-operator
    app.kubernetes.io/part-of: wasp-operator
    app.kubernetes.io/managed-by: kustomize
  name: wasp-editor-role
rules:
- apiGroups:
  - node.kubevirt.io
  resources:
  - wasps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - node.kubevirt.io
  resources:
  - wasps/status
  verbs:
  - get
